### ISSUE TITLE
FFT needs modifications

### ISSUE THREAD

**Issue by hansenms** [ismrmrd/ismrmrd-python-tools#1]
The FFT scaling should reflect the dimensions which have been transformed. At the moment it is scaling for all elements even if they have not been transformed.

**Comment by naegelejd** [comment]
So something like:
```python
img *= np.sqrt(np.prod(np.take(a.shape, dim)))
```
I can fix that now.

**Comment by hansenms** [comment]
That should work.

------

**Comment by inati** [comment]
there was a small typo in the image_to_kspace transform I have pushed a fix.
