### ISSUE TITLE
ISMRMRD Python package to parse ismrmrd_header

### ISSUE THREAD

**Issue by samiravafa** [ismrmrd/ismrmrd-python-tools#19]
Hi,

I have a question regarding reading the specifications of the acquisitions of the Dataset. How can I use ISMRMRD Python package to parse "ismrmrd_header" with python?

I can read the Dataset like the k-space Data and Images, but when I read ismrmrd_header with the following code it is not decoded:

`file = h5py.File(path);
print('Keys:', list(file.keys()));
header = file['ismrmrd_header'][()]`

Keys: ['ismrmrd_header', 'kspace', 'reconstruction_rss']

I was wondering if there is a python code that can parse the header.

Thanks.

**Comment by dchansen** [comment]
You should generally be using the i[smrmrd-python](https://github.com/ismrmrd/ismrmrd-python) library to open the dataset. 
Something like
`parse_header = ismrmrd.xsd.CreateFromDocument(xml_header)`
should work
